#include "Atlas.h"
#include "Knight.h"

Atlas atlas_knight_idle_left;
Atlas atlas_knight_idle_right;
Atlas atlas_knight_start_run_left;
Atlas atlas_knight_start_run_right;
Atlas atlas_knight_run_left;
Atlas atlas_knight_run_right;

Atlas atlas_sword;
Atlas atlas_barb_idle;
Atlas atlas_barb_aim;
Atlas atlas_barb_dash;
Atlas atlas_barb_break;

Atlas animation_silk;
Atlas animation_aim_left;
Atlas animation_aim_right;
Atlas animation_dash_in_air_left;
Atlas animation_dash_in_air_right;
Atlas animation_dash_on_floor_left;
Atlas animation_dash_on_floor_right;
Atlas animation_fall_left;
Atlas animation_fall_right;
Atlas animation_idle_left;
Atlas animation_idle_right;
Atlas animation_jump_left;
Atlas animation_jump_right;
Atlas animation_run_left;
Atlas animation_run_right;
Atlas animation_squat_left;
Atlas animation_squat_right;
Atlas animation_throw_barb_left;
Atlas animation_throw_barb_right;
Atlas animation_throw_sword_left;
Atlas animation_throw_sword_right;
Atlas animation_throw_silk_left;
Atlas animation_throw_silk_right;
Atlas animation_vfx_dash_in_air_left;
Atlas animation_vfx_dash_in_air_right;
Atlas atlas_knight_jump_start_left;
Atlas atlas_knight_jump_start_right;
Atlas atlas_knight_jump_loop_left;
Atlas atlas_knight_jump_loop_right;
Atlas atlas_knight_jump_land_left;
Atlas atlas_knight_jump_land_right;
